[#ftl]
[@b.head/]
  [@b.grid items=exchangeGrades var="exchangeGrade"]
    [@b.gridbar]
       bar.addItem("导出", action.exportData("grade.exchangeStudent.std.user.name:姓名,grade.exchangeStudent.std.person.code:身份证号,grade.exchangeStudent.school.code:转换学校代码,grade.courseCode:原课程来源代码,grade.exchangeStudent.majorName:原专业名称,grade.courseName:原课程名称,grade.exchangeStudent.school.name:原办学机构,grade.exchangeStudent.level.code:原教育层次代码,grade.exchangeStudent.category.code:原教育类别代码,grade.credits:原学分,grade.creditHours:原学时,grade.scoreText:原成绩,grade.acquiredOn:获得时间,grade.exchangeStudent.std.level.code:转换后教育层次代码,course.code:转换后课程代码,course.name:转换后课程名称,course.credits:转换后学分,grade.convertOn:转换时间,grade.exchangeStudent.std.state.major.name:转换后专业名称", "xls", "fileName=学分银行成绩-外校成绩"), "excel.png");
    [/@]
    [@b.row]
      [@b.col title="序号" width="4%"]${exchangeGrade_index+1}[/@]
      [@b.col title="姓名" property="exchangeStudent.std.user.name" width="11%"/]
      [@b.col title="身份证号" property="exchangeStudent.std.person.code"  width="14%"]<span style="font-size:0.7em">${exchangeGrade.exchangeStudent.std.person.code}</span>[/@]
      [@b.col title="原办学机构" property="exchangeStudent.school.name"  width="16%"]
         <span title="${exchangeGrade.exchangeStudent.school.code}" style="font-size:0.7em">${exchangeGrade.exchangeStudent.school.name}</span>
      [/@]
      [@b.col title="原专业" property="exchangeStudent.majorName" width="16%"/]
      [@b.col title="原成绩" property="scoreText" width="6%"/]
      [@b.col title="原学分" property="credits" width="6%"/]
      [@b.col title="获得时间" property="acquiredOn" width="8%"]${exchangeGrade.acquiredOn?string("yyyyMM")}[/@]
      [@b.col title="转换后课程" sortable="false" width="21%"]
        [#if exchangeGrade.courses?size >0 ]
        <span style="font-size:0.8em">[#list exchangeGrade.courses as c]${c.name} ${c.credits}分 [#if c_has_next]<br>[/#if][/#list]</span>
        [#else]--[/#if]
      [/@]
      [@b.col title="转换时间" property="updatedAt" width="8%"]${exchangeGrade.updatedAt?string("yyyyMM")}[/@]
    [/@]
  [/@]
[@b.foot/]
